name: Build Frontend Vite and Push Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create .env.production
        run: |
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production
          echo "VITE_APP_NAME=${{ secrets.VITE_APP_NAME }}" >> .env.production
          echo "VITE_OAUTH_CLIENT_ID=${{ secrets.VITE_OAUTH_CLIENT_ID }}" >> .env.production
          echo "VITE_OAUTH_CLIENT_SECRET=${{ secrets.VITE_OAUTH_CLIENT_SECRET }}" >> .env.production

      - name: Login Docker Hub
        run: docker login \
          -u ${{ secrets.DOCKERHUB_USERNAME }} \
          -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          cd frontend
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/insumax-front:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/insumax-front:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/insumax-front:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/insumax-front:${{ github.sha }}
